//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EHksperiment
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Имя услуг.
    /// </summary>
    // *** Start programmer edit section *** (ИмяУслуг CustomAttributes)

    // *** End programmer edit section *** (ИмяУслуг CustomAttributes)
    [AutoAltered()]
    [Caption("Имя услуг")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИмяУслугE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ИмяУслугL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class ИмяУслуг : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (ИмяУслуг CustomMembers)

        // *** End programmer edit section *** (ИмяУслуг CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ИмяУслуг.Наименование CustomAttributes)

        // *** End programmer edit section *** (ИмяУслуг.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ИмяУслуг.Наименование Get start)

                // *** End programmer edit section *** (ИмяУслуг.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ИмяУслуг.Наименование Get end)

                // *** End programmer edit section *** (ИмяУслуг.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИмяУслуг.Наименование Set start)

                // *** End programmer edit section *** (ИмяУслуг.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ИмяУслуг.Наименование Set end)

                // *** End programmer edit section *** (ИмяУслуг.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИмяУслугE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИмяУслугE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИмяУслугE", typeof(IIS.EHksperiment.ИмяУслуг));
                }
            }
            
            /// <summary>
            /// "ИмяУслугL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИмяУслугL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИмяУслугL", typeof(IIS.EHksperiment.ИмяУслуг));
                }
            }
        }
    }
}
